info:
  app:
    name: trade-order-gateway
    env: local
    ver: v0.0.1

server:
  port: 8088


spring:
  redis: #redis整合
    host: localhost  #q380w42329.imdo.co
    port: 6379
    password: 123456
    database: 3
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

  mvc:  #在springboot2.6.X结合swagger2.9.X会提示documentationPluginsBootstrapper空指针异常，
    #原因是在springboot2.6.X中将SpringMVC默认路径匹配策略MAntPathMatcher更改为athPatternParser,
    #导致出错，解决办法是matching-strategy 切换回之前ant_path_matcher
    pathmatch:
      matching-strategy: ant_path_matcher
  swagger2:
    enabled: true

actions: http://campus.query1.ksyun.com:8089,http://campus.query2.ksyun.com:8089
meta:
  url: http://campus.meta.ksyun.com:8090

