server:
  port: 8089
  tomcat:
    threads:
      max: 20 # 最大工作线程数，默认200，超过加入等待队列，默认是100，当等待队列达到100后， 直接拒绝此次请求返回connection refused。
      min-spare: 5  # 最小工作线程数
    max-connections: 30  # 最大连接数,默认8192，tomcat内tcp连接池的大小
    accept-count: 10 # 挂起的请求队列最大连接数，默认100
    connection-timeout: 60s  # server端的socket超时间，默认60s

info:
  app:
    name: trade-order-api
    env: uat
    ver: v0.0.1

spring:
  datasource:
    url: jdbc:mysql://campus-test.mysql.ksyun.com:8306/test_trade?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 3
    minimum-idle: 2
    username: test
    password: test123
  redis:
    host: campus-test.redis.ksyun.com
    port: 8379
    password: Console2016
    db: 3

meta:
  url: http://campus-test.meta.ksyun.com:8090


