info:
  app:
    name: trade-order-gateway
    env: uat
    ver: v0.0.1

server:
  port: 8088

actions: http://campus-test.query1.ksyun.com:8089/online/trade_order,http://campus-test.query2.ksyun.com:8089/online/trade_order
meta: http://campus.meta.ksyun.com:8090
